server:
  context-path: /pethome
  port: 8088


spring:
  profiles:
    active: dev
################################################################################
  datasource:
    url: jdbc:sqlserver://118.31.9.90:1433;DatabaseName=PawLove
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: petin520
################################################################################
  jpa:
    show-sql: true
################################################################################
  jackson:
    default-property-inclusion: non_null
################################################################################
  http:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
################################################################################

######Custom Configuration
web:
  upload: C:/petlove/upload/
  sms:
    account: whlehuike
    password: Tch147258
    url: http://222.73.117.156/msg/HttpBatchSendSM

picturePath: C:/petlove/upload/

wechat:
  mpAppId: wx41fd8229749f5df8
  mpAppSecret: 76cde729d3bbf04728661309549298f5
  myAppToken: ishumahe160107
  myAppEncodingAESKey: PXIlIEdOXBDmXYKVsFHgvzsOroMPybpvUwujU7ugako

projectUrl:
  wechatMpAuthorize: http://girl.nat300.top
  petHome: http://girl.nat300.top
  xx: http://girl.nat300.top/pethome/wechat/entry

